export default [
    {id:"crack_ROV",
    temporalGroupID:'ardmucknish_bay',
    name: "Ardmucknish Bay",
    url:"https://tiletesting.s3.eu-west-2.amazonaws.com/3dtiles_50/tileset.json",
    year:2023,
    description : "Survey Name : Ardmucknish Bay 2023",
    markerPath : "./alcyonium_digitatum_icon_red.png",
    geojsonPath:"",
    geoJsonHeightAdjust: '',
    verticalOffset :30}
    ,
    {id:"crack_DIVER",
    temporalGroupID:'ardmucknish_bay',
    name: "Ardmucknish Bay",
    url:"https://tiletesting.s3.eu-west-2.amazonaws.com/crack_diver_tiles/tileset.json",
    year:2022,
    description : "Survey Name : Ardmucknish Bay 2022",
    markerPath : "./alcyonium_digitatum_icon_red.png",
    geojsonPath:"./22_Alcyionium.json",
    geoJsonHeightAdjust: -67,
    verticalOffset :30},

    {id:"broad_bay_t2b",
    temporalGroupID:'',
    name: "Broad Bay T2B",
    url:"https://tiletesting.s3.eu-west-2.amazonaws.com/T_2B/tileset.json",
    year:2023,
    description : "Survey Name : Broad Bay Transect 2B",
    markerPath : "./alcyonium_digitatum_icon_red.png",
    geojsonPath:"",
    geoJsonHeightAdjust: '',
    verticalOffset :30},

    {id:"broad_bay_t3c",
    temporalGroupID:'',
    name: "Broad Bay T3C",
    url:"https://tiletesting.s3.eu-west-2.amazonaws.com/T_3C/tileset.json",
    year:2023,
    description : "Survey Name : Broad Bay Transect 3C",
    markerPath : "./alcyonium_digitatum_icon_red.png",
    geojsonPath:"",
    geoJsonHeightAdjust: '',
    verticalOffset :30},

    {id:"broad_bay_t4a",
    temporalGroupID:'',
    name: "Broad Bay T4A",
    url:"https://tiletesting.s3.eu-west-2.amazonaws.com/T_4A/tileset.json",
    year:2023,
    description : "Survey Name : Broad Bay Transect 4A",
    markerPath : "./alcyonium_digitatum_icon_red.png",
    geojsonPath:"",
    geoJsonHeightAdjust: '',
    verticalOffset :30},


    {id:"broad_bay_t4c",
    temporalGroupID:'',
    name: "Broad Bay T4C",
    url:"https://tiletesting.s3.eu-west-2.amazonaws.com/T_4C/tileset.json",
    year:2023,
    description : "Survey Name : Broad Bay Transect 4C",
    markerPath : "./alcyonium_digitatum_icon_red.png",
    geojsonPath:"",
    geoJsonHeightAdjust: '',
    verticalOffset :30}



]